openapi: 3.0.0
info:
  title: node-scim
  description: |
    scim client compatible with scim v2, as defined by:
    - https://datatracker.ietf.org/doc/html/rfc7643
    - https://datatracker.ietf.org/doc/html/rfc7644
  version: "0.0.1"
tags:
  - name: users
  - name: groups
  - name: introspection
paths:
  # TODO: auto-generate references
  /scim/v2/Users:
    $ref: './docs/openapi/users.yaml#/paths/~1scim~1v2~1Users'
  /scim/v2/Users/{id}:
    $ref: './docs/openapi/users.yaml#/paths/~1scim~1v2~1Users~1{id}'
  /scim/v2/Groups:
    $ref: './docs/openapi/groups.yaml#/paths/~1scim~1v2~1Groups'
  /scim/v2/Groups/{id}:
    $ref: './docs/openapi/groups.yaml#/paths/~1scim~1v2~1Groups~1{id}'
  /scim/v2/ServiceProviderConfig:
    $ref: './docs/openapi/introspection.yaml#/paths/~1scim~1v2~1ServiceProviderConfig'
  /scim/v2/ResourceTypes:
    $ref: './docs/openapi/introspection.yaml#/paths/~1scim~1v2~1ResourceTypes'
  /scim/v2/Schemas:
    $ref: './docs/openapi/introspection.yaml#/paths/~1scim~1v2~1Schemas'
