name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: corepack enable
      - run: yarn --immutable

      - run: yarn ci-build

      # TODO: add test suite
      #      - run: yarn ci-test

      - run: yarn ci-lint

      - name: Check for uncommitted changes
        run: ./scripts/assert-clean-working-directory.sh

      # TODO: package as docker image
